[package]
name = "reim_wrap"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.58"
tokio = { version = "1", features = ["full"] }
reim_dt = { path = "../reim_dt" }
futures = "0.3.25"
