[package]
name = "reim_app_codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
mustache = "0.9.0"
serde = "1.0.144"
serde_derive = "1.0.144"
serde_json = "1.0.85"
reim_schema = { path = "../../reim-schema" }
